# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='song_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to=upload.models.filenameChange, verbose_name='Uploaded Image'),
        ),
    ]
