# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20170923_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='user_id',
        ),
    ]
