# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_remove_uploadimage_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='song_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
