#Test with: http://editor.swagger.io/

swagger: '2.0'
info:
  version: 1.0.0
  title: Cover Upload Microservice
  description: Ruby + MySQL Database
  contact:
      name: Group B
      email: juasmartinezbel@unal.edu.co 
  license:
    name: Software Architecture 2017-II
    
host: 192.168.99.101:3005
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:

  /covers:
    get:
      summary: Returns all the covers
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/CoversList"
        '404':
          description: Not Found.
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: Internal Server Error.
          schema:
            $ref: '#/definitions/ErrorModel'
  /covers/{id}:
    get:
      summary: Cover {id} information
      parameters:
        - name: id
          in: path
          description: Returns the cover given it's id
          required: true
          type: integer
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Covers'
        '404':
          description: Not found.
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'    
  /covers/new:
    post:
      summary: Creates a new Cover
      parameters:
        - name: auth
          in: body
          required: true
          description: Creates a new cover in the database
          schema:
            $ref: '#/definitions/CoversCreate'
            
      responses:
        '201':
          description: Cover created successfully.
          schema:
            $ref: "#/definitions/Covers"
        '400':
          description: Bad Request.
          schema:
            $ref: '#/definitions/ErrorModel'
        '422':
          description: Unprocessable Entity.
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: Internal Server Error.
          schema:
            $ref: '#/definitions/ErrorModel'
            
  /covers/{id}/delete:
    delete:
      summary: Delets the Cover identified by {id}
      parameters:
        - name: id
          in: path
          description: Deletes the cover given it's id
          required: true
          type: integer
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/ErrorModel'
        '404':
          description: Not found.
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: Internal Server Error.
          schema:
            $ref: '#/definitions/ErrorModel'
 
definitions:

  CoversCreate:
    type: object
    properties:
      picture:
        type: object
  
  Covers:
    type: object
    properties:
      id:
        type: integer
      picture:
        type: object
  
  CoversList:
    type: array
    items:
        $ref: '#/definitions/Covers'
      
# Errors
  ErrorModel:
    type: object
    required:
      - message
      - code
    properties:
      message:
        type: string
      code:
        type: number
      description:
        type: object
    
