version: '2'
services:
  session_ms:
    build: .
    ports:
      - "3001:3001"
    links:
      - session_db
    depends_on:
      - session_db
  
  session_db:
    image: mysql
    ports:
      - "3303:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: root


